import { server } from '@/Utils/Server'
import Head from 'next/head'
import React from 'react'


export const metadata = {
    title: 'product name',
    description: 'Generated by create next app',
  }
const layout =  ({children}:any) => {

  return (
    <>
    <main >
            {children}
    </main>
    </>
  )
}

export default layout